export const itemsTotal = [
  { id: 'aa', content: 'pth' },
  { id: 'ab', content: 'wxy' },
  { id: 'ac', content: 'lb' },
  { id: 'ad', content: 'rzx' },
  { id: 'ae', content: 'jy' },
  { id: 'af', content: 'zj' },
  { id: 'ag', content: 'lq' },
  { id: 'ah', content: 'yj' },
  { id: 'ba', content: 'zq' },
  { id: 'bb', content: 'zjy' },
  { id: 'bc', content: 'lqy' },
  { id: 'bd', content: 'zxy' },
  { id: 'be', content: 'zzy' },
  { id: 'bf', content: 'lby' },
  { id: 'bg', content: 'jyy' },
  { id: 'bh', content: 'zy' },
  { id: 'ca', content: 'zyy' },
  { id: 'cb', content: 'lyy' },
  { id: 'cc', content: 'zyx' },
  { id: 'cd', content: 'zqy' },
  { id: 'ce', content: 'zyj' },
  { id: 'cf', content: 'lqz' },
  { id: 'cg', content: 'zyq' },
  { id: 'ch', content: 'zjyy' },
  { id: 'da', content: 'lbyy' },
  { id: 'db', content: 'jyyy' },
  { id: 'dc', content: 'zyyy' },
  { id: 'dd', content: 'zyxy' },
  { id: 'de', content: 'zyz' },
  { id: 'df', content: 'zyyx' },
  { id: 'dg', content: 'lyyy' },
  { id: 'dh', content: 'zyjy' },
  { id: 'ea', content: 'lqyy' },
  { id: 'eb', content: 'zqyy' },
  { id: 'ec', content: 'zjyyy' },
  { id: 'ed', content: 'lbxy' },
  { id: 'ee', content: 'lbz' },
  { id: 'ef', content: 'lbj' },
  { id: 'eg', content: 'lbq' },
  { id: 'eh', content: 'lbjy' },
];
export const itemsFromBackend1 = itemsTotal.slice(0, 8);
export const itemsFromBackend2 = itemsTotal.slice(8, 16);
export const itemsFromBackend3 = itemsTotal.slice(16, 24);
export const itemsFromBackend4 = itemsTotal.slice(24, 32);
export const itemsFromBackend5 = itemsTotal.slice(32, 40);

export const answer1 = [
  'eh',
  'ca',
  'ec',
  'ed',
  'ad',
  'ac',
  'ag',
  'ef',
  'da',
  'db',
];
export const answer2 = [
  'bh',
  'dd',
  'ab',
  'df',
  'ah',
  'eg',
  'bg',
  'ea',
  'eb',
  'aa',
];
export const answer3 = [
  'cf',
  'ch',
  'dg',
  'ee',
  'bb',
  'bc',
  'bf',
  'cc',
  'ce',
  'de',
];
export const answer4 = [
  'af',
  'cd',
  'be',
  'dc',
  'cg',
  'cb',
  'ba',
  'dh',
  'ae',
  'bd',
];
